server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configs/

  profiles:
    active: native

# Actuator endpoints for config server
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

logging:
  level:
    org.springframework.cloud.config: DEBUG
